---
name: Generate Deployment Matrix
description: |
  Generates a deployment matrix based on changed files (using a pre-defined filter). For each
  matched path it will try to lookup the key, or default to the provided default
  key.
inputs:
  filter-file:
    description: Path to the filter file
    required: true
  changes-override:
    description: |
      Override the changes filter and provide your own set of paths (comma separated). If you
      provide the magic value `_all_`, it'll use all the paths from the filter file.
    required: false
  default-key:
    description: Default key (fallback value if no key is provided for a path)
    required: false
    default: Default
  output-key-name:
    description: Name for the output key (defaults to `environment`)
    required: false
    default: environment
outputs:
  matrix:
    description: List of combinations of paths & keys
    value: ${{ steps.matrix-generator.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Simplify filter file
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/simplify-filter-file.sh \
          ${{ inputs.filter-file }} \
          /tmp/simple-path-filters.yaml
    # Collect changed paths
    - name: Collect changes
      if: "${{ inputs.changes-override == '' }}"
      id: filtered
      uses: dorny/paths-filter@v3
      with:
        filters: /tmp/simple-path-filters.yaml
    - name: Collect changes
      if: "${{ inputs.changes-override == '_all_' }}"
      id: all
      shell: bash
      run: |
        echo "changes=`${{ github.action_path }}/scripts/generate-all-keys.sh \
          /tmp/simple-path-filters.yaml`" >> "$GITHUB_OUTPUT"
    - name: Collect changes
      id: custom
      shell: bash
      run: |
        echo "changes=`${{ github.action_path }}/scripts/process-manual-keys.sh \
          '${{ inputs.changes-override }}'`" >> "$GITHUB_OUTPUT"
    # Post process into actual matrix
    - name: Generate Matrix
      id: matrix-generator
      shell: bash
      run: |
        CHANGED_PATHS='${{ steps.filtered.outputs.changes || steps.all.outputs.changes || steps.custom.outputs.changes }}'
        echo "matrix=`${{ github.action_path }}/scripts/generate-matrix.sh \
          <(echo $CHANGED_PATHS) \
          ${{ inputs.filter-file }} \
          ${{ inputs.output-key-name }} \
          ${{ inputs.default-key }}
          `" >> "$GITHUB_OUTPUT"
